[tool.poetry]
name = "microdata-datastore-version-manager"
version = "0.0.1"
description = ""
authors = ["microdata <microdata-dev@ssb.no>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
